[tool.poetry]
name = "backend"
version = "0.1.0"
description = "Fast API Backend for Python Learning Club website"
authors = ["steven <msycomtw@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.110.3"
uvicorn = "^0.29.0"
sqlalchemy = "^2.0.29"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
